Namespacename: game-2048

Deploymentname: deployment-2048

Servicename: service-2048

Ingressname: ingress-2048

labels:
  app.kubernetes.io/name: app-2048
 
matchLabels:
  app.kubernetes.io/name: app-2048
  
selector:
  app.kubernetes.io/name: app-2048

containers:
  name: app-2048
  image: 239232208597.dkr.ecr.us-east-1.amazonaws.com/demo-ecr-php:latest
  imagePullPolicy: Always
  
annotations:
  kubernetes.io/ingress.class: alb
  alb.ingress.kubernetes.io/scheme: internet-facing
  alb.ingress.kubernetes.io/target-type: instance
